//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVC.ServiceReference1.HelloWorldResponse HelloWorld(MVC.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC.ServiceReference1.HelloWorldResponse> HelloWorldAsync(MVC.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ReadFileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadFile", ReplyAction="*")]
        MVC.ServiceReference1.ReadFileResponse ReadFile(MVC.ServiceReference1.ReadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC.ServiceReference1.ReadFileResponse> ReadFileAsync(MVC.ServiceReference1.ReadFileRequest request);
        
        // CODEGEN: Generating message contract since element name books from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteFile", ReplyAction="*")]
        MVC.ServiceReference1.WriteFileResponse WriteFile(MVC.ServiceReference1.WriteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteFile", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC.ServiceReference1.WriteFileResponse> WriteFileAsync(MVC.ServiceReference1.WriteFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVC.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVC.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVC.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadFile", Namespace="http://tempuri.org/", Order=0)]
        public MVC.ServiceReference1.ReadFileRequestBody Body;
        
        public ReadFileRequest() {
        }
        
        public ReadFileRequest(MVC.ServiceReference1.ReadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadFileRequestBody {
        
        public ReadFileRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC.ServiceReference1.ReadFileResponseBody Body;
        
        public ReadFileResponse() {
        }
        
        public ReadFileResponse(MVC.ServiceReference1.ReadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC.ServiceReference1.ArrayOfString ReadFileResult;
        
        public ReadFileResponseBody() {
        }
        
        public ReadFileResponseBody(MVC.ServiceReference1.ArrayOfString ReadFileResult) {
            this.ReadFileResult = ReadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteFile", Namespace="http://tempuri.org/", Order=0)]
        public MVC.ServiceReference1.WriteFileRequestBody Body;
        
        public WriteFileRequest() {
        }
        
        public WriteFileRequest(MVC.ServiceReference1.WriteFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVC.ServiceReference1.ArrayOfString books;
        
        public WriteFileRequestBody() {
        }
        
        public WriteFileRequestBody(MVC.ServiceReference1.ArrayOfString books) {
            this.books = books;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVC.ServiceReference1.WriteFileResponseBody Body;
        
        public WriteFileResponse() {
        }
        
        public WriteFileResponse(MVC.ServiceReference1.WriteFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WriteFileResponseBody {
        
        public WriteFileResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : MVC.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<MVC.ServiceReference1.WebService1Soap>, MVC.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC.ServiceReference1.HelloWorldResponse MVC.ServiceReference1.WebService1Soap.HelloWorld(MVC.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MVC.ServiceReference1.HelloWorldRequest inValue = new MVC.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MVC.ServiceReference1.HelloWorldRequestBody();
            MVC.ServiceReference1.HelloWorldResponse retVal = ((MVC.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC.ServiceReference1.HelloWorldResponse> MVC.ServiceReference1.WebService1Soap.HelloWorldAsync(MVC.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            MVC.ServiceReference1.HelloWorldRequest inValue = new MVC.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MVC.ServiceReference1.HelloWorldRequestBody();
            return ((MVC.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC.ServiceReference1.ReadFileResponse MVC.ServiceReference1.WebService1Soap.ReadFile(MVC.ServiceReference1.ReadFileRequest request) {
            return base.Channel.ReadFile(request);
        }
        
        public MVC.ServiceReference1.ArrayOfString ReadFile() {
            MVC.ServiceReference1.ReadFileRequest inValue = new MVC.ServiceReference1.ReadFileRequest();
            inValue.Body = new MVC.ServiceReference1.ReadFileRequestBody();
            MVC.ServiceReference1.ReadFileResponse retVal = ((MVC.ServiceReference1.WebService1Soap)(this)).ReadFile(inValue);
            return retVal.Body.ReadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC.ServiceReference1.ReadFileResponse> MVC.ServiceReference1.WebService1Soap.ReadFileAsync(MVC.ServiceReference1.ReadFileRequest request) {
            return base.Channel.ReadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceReference1.ReadFileResponse> ReadFileAsync() {
            MVC.ServiceReference1.ReadFileRequest inValue = new MVC.ServiceReference1.ReadFileRequest();
            inValue.Body = new MVC.ServiceReference1.ReadFileRequestBody();
            return ((MVC.ServiceReference1.WebService1Soap)(this)).ReadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC.ServiceReference1.WriteFileResponse MVC.ServiceReference1.WebService1Soap.WriteFile(MVC.ServiceReference1.WriteFileRequest request) {
            return base.Channel.WriteFile(request);
        }
        
        public void WriteFile(MVC.ServiceReference1.ArrayOfString books) {
            MVC.ServiceReference1.WriteFileRequest inValue = new MVC.ServiceReference1.WriteFileRequest();
            inValue.Body = new MVC.ServiceReference1.WriteFileRequestBody();
            inValue.Body.books = books;
            MVC.ServiceReference1.WriteFileResponse retVal = ((MVC.ServiceReference1.WebService1Soap)(this)).WriteFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC.ServiceReference1.WriteFileResponse> MVC.ServiceReference1.WebService1Soap.WriteFileAsync(MVC.ServiceReference1.WriteFileRequest request) {
            return base.Channel.WriteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceReference1.WriteFileResponse> WriteFileAsync(MVC.ServiceReference1.ArrayOfString books) {
            MVC.ServiceReference1.WriteFileRequest inValue = new MVC.ServiceReference1.WriteFileRequest();
            inValue.Body = new MVC.ServiceReference1.WriteFileRequestBody();
            inValue.Body.books = books;
            return ((MVC.ServiceReference1.WebService1Soap)(this)).WriteFileAsync(inValue);
        }
    }
}
